### PR TITLE
also type check httpx interfaces

### PR DESCRIPTION
**Pull request by ojii**
Correctly types the timeout option in `create_client`.

### CODE REVIEW

**Comment by ojii** [comment]
> This is black magic to me.
> I'd rather see type hints as _hints_, in which case run-time (?) `cast` is a bit odd...
> Overall, if it works, merge away!

The `cast` calls in `typing_workarounds.py` are hopefully temporary until attrs updates with fixed type hints. `cast` is not actually a runtime thing, it returns its second argument unchanged. The purpose of them is to tell a type checker (such as `mypy`) to ignore the types it has computed for the second argument and instead use the type given as the first argument as its type.

This is also the reason why I haven't merged this yet, I'm hoping to remove those hacks if attrs releases soon.

**Comment by dimaqq** [comment]
> > This is black magic to me.
> > I'd rather see type hints as _hints_, in which case run-time (?) `cast` is a bit odd...
> > Overall, if it works, merge away!
> 
> The `cast` calls in `typing_workarounds.py` are hopefully temporary until attrs updates with fixed type hints. `cast` is not actually a runtime thing, it returns its second argument unchanged. The purpose of them is to tell a type checker (such as `mypy`) to ignore the types it has computed for the second argument and instead use the type given as the first argument as its type.
> 
> This is also the reason why I haven't merged this yet, I'm hoping to remove those hacks if attrs releases soon.

I see no problem with releasing as is and then following up with another release for new attrs :)

**Comment by ojii** [comment]
replaced GitHub Workflows with CircleCI to better control Python/tools versions.

**Comment by dimaqq** [comment]
You may want to bump up version in `pyproject.toml`

**Pull request merged**
