### PR TITLE
Add GHA to release to PyPI

### PR DESCRIPTION
**Pull request by FurqanHabibi**
- PyPI release triggered on new Github release.
- Checks release branch is the default branch (default).
- Checks release tag name matches package version.
- Release using [pypi trusted pubishing](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/).

### CODE REVIEW

**Comment by ojii** [comment]
@FurqanHabibi could you update/change this to use https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ instead?

**Comment by FurqanHabibi** [comment]
@ojii Updated to use trusted publishing.

Set up on pypi side as well.
image

**Comment by ojii** [comment]
could you rebase this onto the default branch?

**Comment by FurqanHabibi** [comment]
@ojii Rebase is done.
Added concurrency to workflow.yml as well to stop ongoing workflow when new run starts.

**Pull request merged**
